const Routes = {
	LOADING: "LOADING",

	LOGIN_STACK: "LOGIN_STACK",
	LOGIN_SCREEN: "LOGIN_SCREEN",

	MAIN_APP: "MAIN_APP",
	HOME_SCREEN: "HOME_SCREEN",
	SETTINGS_SCREEN:'SETTINGS',
	EDIT_SETTING:'EDIT_SETTING',
};

export default Routes;
